### ISSUE TITLE
Can I  output flv buffer with IFVideoPicker?

### ISSUE THREAD

**Issue by aquaibm** [minsikzzang/IFVideoPicker#2]
IFVideoEncoder *ve =
  [IFVideoEncoder createH264VideoWithDimensions:dimensions
                                        bitRate:500000
                                    maxKeyFrame:200];

[videoPicker_ startCaptureWithEncoder:ve
                                audio:ae
                         captureBlock:^(NSArray *frames, NSData *buffer) {
                        // Captured MP4 frames are coming
                        NSLog(@"buffer: %d bytes, with %d frames", [buffer length], [frames count]);
                    } metaHeaderBlock:^(MP4Reader *reader) {}
                        // MP4 moov header coming
                       } failureBlock:^(NSError *error) {
                        // Failed to capture video / audio chunk
                    }];

In the captureBlock,buffer is mp4, now I want to convert mp4 to flv, so I can stream it to a rtmp server with rtmp-wrapper's help .
How can I do that? Thanks.

**Comment by aquaibm** [comment]
Got it , now using FLVWriter.

**Comment by loksurya** [comment]
@aquaibm how did you use FLVWriter to stream to rtmp server ?
